language: python
python:
  - "2.6"
  - "2.7"
  # - "3.2"
install:
  - "pip install -r requirements.txt"
script:
  - "PATH=$PATH:/tmp/bin project/manage.py test"
  - "PATH=$PATH:/tmp/bin project/manage.py lettuce -d --settings=envs.lettuce"
